feat: add calendarDate and calendarDateRange
gastromatic/calendar-date pull request #2
Opened 2021-03-08 18:45 UTC by co-sic

2021-03-09 15:24 UTC, dimitriSaplatkin requested changes

2021-03-09 15:24 UTC, dimitriSaplatkin commented on src/CalendarDate.ts
> +      if (day < 1 || day > 31) {
you are catching in line 60 that day can be bigger then max days of month. Why we need a guarding block here? The same we can also do for month number

2021-03-09 15:24 UTC, dimitriSaplatkin commented on src/CalendarDate.ts
> +      }
```suggestion
      const maxDayOfMonth = month === 1 && CalendarDate.isLeapYear(year) ? 29 : daysInMonth[month];
```

2021-03-09 15:24 UTC, dimitriSaplatkin commented on src/CalendarDate.ts
> +      `CalendarDate Validation Error: Input ${isoString.toString()} is not a valid ISO Date String.`,
```suggestion
      `CalendarDate Validation Error: Input ${isoString.toString()} is not a valid ISO Date String YYYY-MM-DD.`,
```

2021-03-09 15:24 UTC, dimitriSaplatkin commented on src/CalendarDate.ts
> +  isInsideOfDateRange(calendarDateRange: CalendarDateRange): boolean {
i would keep calenderdate independet from CalenderDate and move it to CalenderDateRange and pass the date instead

2021-03-09 15:24 UTC, dimitriSaplatkin commented on src/CalendarDateRange.ts
> +    if (!autoArrange && end < start) {
I would set autoArrange to a boolean if not defined

2021-03-09 15:24 UTC, dimitriSaplatkin commented on src/CalendarDateRange.ts
> +        `CalendarDateRange Validation Error: Input ${string.toString()} is not valid.`,
```suggestion
        `CalendarDateRange Validation Error: Input ${string.toString()} is not valid. Passed string should have the pattern YYYY-MM-DD/YYYY-MM-DD`,
```

2021-03-09 15:24 UTC, dimitriSaplatkin commented on src/CalendarDateRange.ts
> +    const split = string.split('/');
maybe it makes sense to check via regEx. What do you think?

2021-03-09 15:24 UTC, dimitriSaplatkin commented on src/CalendarDateRange.ts
> +  isInsideOfDateRange(calendarDateRange: CalendarDateRange): boolean {
Can we talk about this function?

2021-03-12 15:36 UTC, kkhanhluu approved these changes

2021-03-15 06:14 UTC, dimitriSaplatkin requested changes

2021-03-15 06:14 UTC, dimitriSaplatkin commented on src/CalendarDateRange.ts
> +  ): boolean;
what is the porpuse of defining this parts?

2021-03-15 06:14 UTC, dimitriSaplatkin commented on test/helpers.ts
> +export function ensureValidDay(year: number, month: number, day: number): number {
why this function is not tested in own file as an official helper method?

2021-03-15 10:52 UTC, dimitriSaplatkin submitted a review, later dismissed

2021-03-15 11:40 UTC, dimitriSaplatkin requested changes

2021-03-15 11:40 UTC, dimitriSaplatkin commented on src/CalendarDate.ts
> +  public static isLeapYear(year: number) {
public static isLeapYear(year: number): boolean {

2021-03-15 12:53 UTC, dimitriSaplatkin approved these changes

2021-03-15 12:56 UTC, merged