feat: add isEqualsOrBefore and isEqualsOrAfter methods
gastromatic/calendar-date pull request #286
Opened 2024-03-07 10:13 UTC by batrdn

### Overview

Added `isBeforeOrEqual` and `isAfterOrEqual` methods to shorten what would otherwise be written as:
`date1.isAfter(date2) || date1.equals(date2)` or `date1.isBefore(date2) || date1.equals(date2)`

2024-03-07 13:01 UTC, dimitriSaplatkin requested changes

2024-03-07 13:01 UTC, dimitriSaplatkin commented on src/CalendarDate.ts
> +    return this.isAfter(calendarDate) || this.equals(calendarDate);
```suggestion
    return this.valueOf() >= calendarDate.valueOf();
```

2024-03-07 13:03 UTC, co-sic requested changes
update README with new functions

2024-03-07 13:21 UTC, dimitriSaplatkin approved these changes

2024-03-08 09:10 UTC, co-sic approved these changes

2024-03-08 09:11 UTC, merged